### ISSUE TITLE
Integrate with TinyMCE

### ISSUE THREAD

**Issue by alfiyan28** [victorjonsson/jQuery-Form-Validator#422] opened 2016-04-02 02:15 UTC
I'm using WSYISYG tinyMCE https://www.tinymce.com/ 

when I use normal textarea, validator works well, but when I add tinyMCE the validator can't work?

**Comment by victorjonsson** [comment] 2016-04-19 09:53
Duplicate of #324

**Closed by victorjonsson** 2016-04-19 09:53 UTC

**Comment by victorjonsson** [comment] 2016-05-18 12:52
Here's a quick and dirty fix https://github.com/victorjonsson/jQuery-Form-Validator/issues/324#issuecomment-220016075
