### ISSUE TITLE
Can't use module sanitize with javascript validation config

### ISSUE THREAD

**Issue by thwuersch** [victorjonsson/jQuery-Form-Validator#350] opened 2015-11-30 09:27 UTC
I have this code in my validation config (using the `jsconf` module):
```js
    validate: {
      ...
      '#income': {
        validation: 'number',
        'sanitize': 'numberFormat',
        'sanitize-number-format': '0,0.00'
      },
      ...
    }
```

then I get this attributes

input id="income" name="income" type="text" class="form-control valid" value="10000" data-validation="number" data-validation-sanitize="numberFormat" data-validation-sanitize-number-format="0,0.00"

instead of 

input id="income" name="income" type="text" class="form-control valid" value="10000" data-validation="number" data-sanitize="numberFormat" data-sanitize-number-format="0,0.00"

**Comment by victorjonsson** [comment] 2015-11-30 10:33
Ah, yes. You will have to do a dirty fix for this one.  

The problem is that the `jsconf` module only lets you declare attributes that should be prefixed with `data-validation-` . I'm thinking that you could use `_` to add an attribute that shouldn't be prefixed.

```js
var validations = {
    '#income': {
      validation: 'number',
      '_data-sanitize': 'numberFormat',
      '_data-sanitize-number-format': '0,0.00'
    }
};

**Comment by thwuersch** [comment] 2015-12-01 08:08
My dirty fix to ```jsconf``` to support the ```sanitize``` attributees 

```javascript
(function($) {

  'use strict';

  $.setupValidation = function(conf) {
    var $forms = $(conf.form || 'form');
    $.each(conf.validate || conf.validation || {}, function(elemRef, attr) {
        var $elem;
        if ( elemRef[0] === '#' ) {
          $elem = $(elemRef);
        }
        else if ( elemRef[0] === '.' ) {
          $elem = $forms.find(elemRef);
        }
        else {
          $elem = $forms.find('*[name="' +elemRef+ '"]');
        }

        $elem.attr('data-validation', attr.validation);

        $.each(attr, function(name, val) {
          if( name !== 'validation' && val !== false) {
            if( val === true ){
              val = 'true';
            }
            if (name.substring(0, 8) !== 'sanitize') {
              $elem.valAttr(name, val);
            } else {
              $elem.attr('data-' + name, val);
            }
          }
        });
    });

    $.validate(conf);
  };

})(jQuery);
```

**Closed** 2016-05-19 08:12 UTC
Labels: Fixed in next release, Improvement
