### ISSUE TITLE
Optional Number fields

### ISSUE THREAD

**Issue by haxtrujillo** [victorjonsson/jQuery-Form-Validator#388] opened 2016-02-22 19:02 UTC
Number fields that are not required should not be validated, otherwise the field required to enter at least one number.

**Comment by victorjonsson** [comment] 2016-02-22 19:10
http://www.formvalidator.net/#default-validators_optional

**Comment by haxtrujillo** [comment] 2016-02-22 19:14
It doesn't work. I am using the html5 plugin, even setting to be optional the validator requires a number.

**Comment by ray-print** [comment] 2016-02-28 08:18
Duplicate of #315? If so, that should be fixed in the next release.

**Closed** 2016-05-19 08:16 UTC
Labels: Fixed in next release, Unconfirmed
