### ISSUE TITLE
Incorrect validation on focus

### ISSUE THREAD

**Issue by treiber** [victorjonsson/jQuery-Form-Validator#405] opened 2016-03-09 19:00 UTC
So I stumbled upon this issue which is problematic for me since the `has-success` class triggers a  CSS animation:

http://www.formvalidator.net/#reg-form
1. Enter invalid Email Address
2. Click on User Name
   --> blur event is called and email address becomes invalid
3. Go back to Email Address and enter valid email.
   --> Immediately the field gets validated.
4. Go to next / other Input
5. Go back to Email Address input
   --> The validation is triggered right away again causing the css class to be removed and appended again (I think even multiple times) - you can see this in the developer tools.

Is that expected behavior? The removing and reappending of the `has-success` class causes my animation to start when it really doesn't feel necessary.

**Comment by victorjonsson** [comment] 2016-03-10 17:18
This is the expected behaviour. But that doesn't mean it can't be changed for the better.

Is it some library that provides this css-animation or are you in control of choosing the class name for the animation?

**Comment by treiber** [comment] 2016-03-14 15:51
I'm in control of choosing the class name - In fact, it get's targeted with the class I set in the `inputParentClassOnSuccess` option.

**Comment by victorjonsson** [comment] 2016-03-14 18:06
So if I understand you correctly, all you have to do inorder to solve the problem is to change the value on  'inputParentClassOnSuccess` from has-success to something else?

**Comment by treiber** [comment] 2016-03-14 18:10
No. The animation is triggered as soon as the class is set (independent of the actual class name). The issue I have is the immediate, and multiple removing and resetting of the class in point 5 above - causing the animation to trigger when it doesn't really make sense...

Should I prepare a code-sample to illustrate?

**Comment by victorjonsson** [comment] 2016-03-14 18:11
Okey, is this an animation that you want to trigger once the input is successfully validated?

**Comment by victorjonsson** [comment] 2016-03-14 18:12
I understand the problem but if you could provide me with an example that would be great

**Comment by victorjonsson** [comment] 2017-03-14 08:58
I'm closing this for now.

**Closed by victorjonsson** 2017-03-14 08:58 UTC
