### ISSUE TITLE
When clicking on Cancel button, onBlur of selected field is fired, shows error, and stops cancel button from being clicked.

### ISSUE THREAD

**Issue by renzska** [victorjonsson/jQuery-Form-Validator#418] opened 2016-03-22 16:20 UTC
When clicking on Cancel or Submit button, the onBlur of the selected field is fired, shows error, and stops the button from being clicked. How I can keep validateOnBlur enabled, but still allow the cancel or submit button to be clicked? At this point, the validation steals the click and the user has to click the cancel button again because it was never actually clicked.

Thanks,

John

**Comment by victorjonsson** [comment] 2016-04-19 10:05
I'm not able to reproduce this. Please provide me with some code so I can investigate this further.

**Comment by xonecas** [comment] 2016-06-27 22:39
I was able to reproduce:

Make sure validateOnBlur is set to true, focus a required field (with `validation="required"`) then press the reset button. The event `validate` happens but reset is never called.

**Comment by victorjonsson** [comment] 2016-06-28 12:01
Hm I'm not sure if this is a real issue. I'm guessing most people will understand what happens, that the press of the button misses the target because the button element gets pushed downwards. All the user has to do is to press the button once more.

This is only an issue when the following is true:

- You use validateOnBlur (which is default)
- You have css rules that places the error message below the input (which is rather common)
- The input that is being focused on has not yet become validated and has an invalid value.
- The button being pressed is of type reset. (If it's a submit button it doesn't really matter, its either valid and everything goes fine or the user gets noticed that the input has an invalid value).

**Comment by xonecas** [comment] 2016-06-29 21:40
It's a real issue, it's not ok to have the user click Cancel twice because the action is being prevented on the first click.

**Comment by victorjonsson** [comment] 2016-08-09 09:30
I still consider this an edge case. 

I'm not sure how to solve this issue either. The first thing that happens when you press down the mouse button is that the blur event gets triggered on the currently focused input. This will dispatch the validation, and if value is invalid the error message will be added to the DOM. Then when you lift your finger from the mouse button the actual click event will take place. Now the reset-button might have moved, and if too small, the mouse click will miss the button.

The solution to this is to either set `validateOnBlur` to false or place the error messages somewhere they don't have any effect on the height of the form.

I will close this for now but I'm open for suggestions...

**Closed by victorjonsson** 2016-08-09 09:30 UTC
Labels: Unconfirmed
