### ISSUE TITLE
File Validation

### ISSUE THREAD

**Issue by evanfa** [victorjonsson/jQuery-Form-Validator#167] opened 2014-08-07 07:26 UTC
Hi I´m not really sure if is a bug.
But I tried to use the file validation into my form but after try in many ways to process the form is unsuccessful.

The real (and disturbing) problem is that after check the console I get this:
Input "myfile" is about to become validated test.php:69
Input "myfile" is VALID test.php:72
Validation Fail 

"myfile" is the file tag... and every others validation  are OK! but after this the validation fails and get a error message. I think that the problem is the file validation, I´m using the chrome and loaded the "file.js" but does not work!

Anyone  have an idea?
Greeting!.

**Comment by Lindsayanng** [comment] 2015-02-19 18:08
I am also having an issue with file validation. I can not get it to work (currently testing on Chrome Version 40.0.2214.111 (64-bit))/ 

My input looks like this: 
  <input type="file" name="thumbnail" id="thumbnail" data-validation="mime size"
               data-validation-allowing="jpg, png, gif"
                data-validation-max-size="512kb"
                data-validation-error-msg="You have to upload at least two images (max 512kb each)"/>

When I click the input immediate this error shows up in the console before a file is even selected: 
Uncaught Error: Using undefined validator "validate_mime"

Once a file is selected I get this error again":
Uncaught Error: Using undefined validator "validate_mime"

and again on submission I get 
Uncaught Error: Using undefined validator "validate_mime"


This exists when I also check for file extension or size. The same error except different "validator" listed. 

I have also noticed that chrome reads a pdf as an image with the message: 
 Resource interpreted as Image but transferred with MIME type application/pdf: 

I don;t know if that is fixed via your script when it is working properly though. I have been unable to get the mime type validator to work so I can not say.

**Comment by victorjonsson** [comment] 2015-02-20 07:09
Could you please paste in the entire code.

**Comment by Lindsayanng** [comment] 2015-02-24 21:17
This is my code to trigger the validator 

``var $messages = jQuery('#error-message-wrapper');
jQuery.validate({
  form : '#eventsubmission',
//    errorMessagePosition : $messages,
    modules : ' security',
    onError : function() {
        /*put fail message here */
       },
      modules : 'file',
       decimalSeparator : '.'
});``

**Comment by Lindsayanng** [comment] 2015-02-24 21:19
Here is my HTML code 

``    <div id="fileupload">
              <input type="file" name="thumbnail" id="thumbnail" 
              data-validation-allowing="jpg, png, gif"
              data-validation-max-size="512kb"
              data-validation-error-msg="You have to upload at least two images (max 512kb each)" 
              />
               <span id="fileSelect">Select some files</span>
    </div>``

**Comment by Lindsayanng** [comment] 2015-03-31 22:01
Any new thoughts on this?

**Comment by victorjonsson** [comment] 2015-04-01 07:36
The problem is that you have two declarations of the modules that should be downloaded. It should instead look like:

```js
var $messages = jQuery('#error-message-wrapper');
jQuery.validate({
   form : '#eventsubmission',
   modules : 'security, file',
   onError : function() {
        /* put fail message here */
   },
   decimalSeparator : '.'
});
```

Let me know if you have any more problems!

**Closed by victorjonsson** 2015-04-01 07:36 UTC
Labels: Bug, Unconfirmed

**Comment by Lindsayanng** [comment] 2015-04-01 16:42
OMG. I feel like a dope. Thanks for that
